# Site settings
title: iNat-Tools
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Tools by James Mickley for working with the iNaturalist API
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://yourusername.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mickley # Optional: Your GitHub username
#twitter_username: your_twitter_handle # Optional: Your Twitter username
show_downloads: false # Set to false to hide the "Download" links

# Build Settings
theme: jekyll-theme-architect
markdown: kramdown # default
plugins:
  - jekyll-seo-tag
  # Add other Jekyll plugins here if needed
  # - jekyll-remote-theme # Uncomment and use with remote_theme if not using a supported GitHub Pages theme
